#!/bin/sh
#
#       __      _       _
#  ___ / _| ___| |_ ___| |__
# / __| |_ / _ \ __/ __| '_ \
# \__ \  _|  __/ || (__| | | |
# |___/_|  \___|\__\___|_| |_|
# speedie's stupid fetch tool
# Version something
############################################################
clear

if [[ -f "/etc/os-release" ]]; then
    os="$(cat /etc/os-release)"
elif [[ -f "/System/Library/CoreServices/SystemVersion.plist" ]]; then
	mac="$(cat /System/Library/CoreServices/SystemVersion.plist)" && macmodel="$(sysctl hw.model | sed 's/hw.model: //')"
fi

if [[ -f "/lib/systemd/systemd" ]]; then
	init="systemd"
elif [[ -f "/sbin/openrc" ]]; then
	init="OpenRC"
elif [[ -f "/usr/local/bin/runsvdir" ]]; then
	init="runit"
elif [[ -f "/usr/bin/s6-rc" ]]; then
	init="s6"
fi

# Gentoo first because Gentoo is based
if [[ $os =~ "Gentoo" ]]; then
	os="Gentoo" && art="Gentoo"
elif [[ $os =~ "Funtoo" ]]; then
	os="Funtoo" && art="Funtoo"
elif [[ $os =~ "Arch" ]]; then
	os="Arch" && art="Arch"
elif [[ $os =~ "Debian" ]]; then
	os="Debian" && art="Linux"
elif [[ $os =~ "Pear" ]]; then
	os="ShitOS" && art="Linux"
elif [[ $os =~ "Ubuntu" ]]; then
	os="Ubuntu" && art="Linux"
elif [[ $os =~ "Fedora" ]]; then
	os="Fedora" && art="Linux"
elif [[ $os =~ "Cutefish" ]]; then
	os="ShitFish OS" && art="Linux"
elif [[ $os =~ "Manjaro" ]]; then
	os="Manjarno" && art="Linux"
elif [[ $os =~ "ANSI" ]]; then
	os="$(uname -s)" && art="Linux"
elif [[ $mac =~ "Mac OS X" ]]; then
	os="Mac OS X" && art="Mac OS X"
elif [[ $mac =~ "macOS" ]]; then
	os="macOS" && art="Mac OS X"
elif [[ $mac =~ "Project 081" ]]; then
    os="Project 081" && art="Project 081"
fi

# Base
user="$(whoami)"
host="$(hostname)"

# Data
kernel="$(uname -sr)" # Get kernel version
shell="$(basename "${SHELL}")"
pkg="$(ls -d /var/db/pkg/*/* | wc -l)"
cpu="$(uname -p)"
totalram="$(cat /proc/meminfo | grep -i 'memtotal' | grep -o '[[:digit:]]*' | awk '{$1=$1/1024; print $1,"MB";}')"
usedram="$(cat /proc/meminfo | grep -i 'Active:' | grep -o '[[:digit:]]*' | awk '{$1=$1/1024; print $1,"MB";}' | awk 'NR!=2')"

# Label/Icons
kernelicon="KERNEL:"
osicon="OS:"
shellicon="SHELL:"
pkgicon="PACKAGES:"
macicon="MAC:"
cpuicon="CPU:"
initicon="INIT:"
usedramicon="USED:"
ramicon="RAM:"

#os="Arch" # For testing only
#art="Linux" # For testing only
#tput setaf 3; echo $user@$host" # For testing only

# Display everything to the user!
# NOTE: Ascii must be 8 lines in height!

if [[ $art = "Gentoo" ]]; then
tput setaf 3; echo "                 $user@$host"
tput setaf 5; echo "    dSSSSSb.     $osicon $(tput sgr0)       $os"
tput setaf 5; echo " .dSSSSSSSSSb.   $kernelicon $(tput sgr0)   $kernel"
tput setaf 5; echo " SSSS( )SSSSSSb  $shellicon $(tput sgr0)    $shell"
tput setaf 5; echo " QSSSSSSSSSSSSSb $pkgicon $(tput sgr0) $pkg"
tput setaf 5; echo "   dSSSSSSSSSSP  $cpuicon $(tput sgr0)      $cpu"
tput setaf 5; echo "  dSSSSSSSSSP    $ramicon $(tput sgr0)      $totalram" 
tput setaf 5; echo " SSSSSSSSSSP     $usedramicon $(tput sgr0)     $usedram "
tput setaf 5; echo "  QSSSSSSP       $initicon $(tput sgr0)     $init"
fi

if [[ $art =~ "Arch" ]]; then
tput setaf 3; echo "                 $user@$host"
tput setaf 6; echo "       .        $osicon $(tput sgr0)         $os"
tput setaf 6; echo "      /#\       $kernelicon $(tput sgr0)     $kernel"
tput setaf 6; echo "     /###\      $shellicon $(tput sgr0)      $shell"
tput setaf 6; echo "    /p^###\     $pkgicon $(tput sgr0)   $pkg"
tput setaf 6; echo "   /##P^q##\    $cpuicon $(tput sgr0)        $cpu"
tput setaf 6; echo "  /##(   )##\   $ramicon $(tput sgr0)        $totalram"
tput setaf 6; echo " /###q#    ,^\  $usedramicon $(tput sgr0)       $usedram"
tput setaf 6; echo "/P^         ^q\ $initicon $(tput sgr0)       $init"
fi

if [[ $art =~ "Project 081" ]]; then
tput setaf 3; echo  "               $user@$host"
tput setaf 6; echo  " Y88b   d88P  $osicon $(tput sgr0)     $os"
tput setaf 6; echo  "  Y88b d88P   $kernelicon $(tput sgr0) $kernel"
tput setaf 6; echo  "   Y88o88P    $shellicon $(tput sgr0)  $shell"
tput setaf 6; echo  "    Y888P     $macicon $(tput sgr0) $macmodel"
tput setaf 6; echo  "    d888b     $cpuicon $(tput sgr0)    $cpu"
tput setaf 6; echo  "   d88888b    $ramicon $(tput sgr0)    $totalram"
tput setaf 6; echo  "  d88P Y88b   $usedramicon $(tput sgr0)   $usedram"
tput setaf 6; echo  " d88P   Y88b  $(tput sgr0) "
fi

if [[ $art =~ "Mac OS X" ]]; then
tput setaf 3; echo  "               $user@$host"
tput setaf 0; echo  " Y88b   d88P  $osicon $(tput sgr0)     $os"
tput setaf 0; echo  "  Y88b d88P   $kernelicon $(tput sgr0) $kernel"
tput setaf 0; echo  "   Y88o88P    $shellicon $(tput sgr0)  $shell"
tput setaf 0; echo  "    Y888P     $macicon $(tput sgr0) $macmodel"
tput setaf 0; echo  "    d888b     $cpuicon $(tput sgr0)    $cpu"
tput setaf 0; echo  "   d88888b    $ramicon $(tput sgr0)    $totalram"
tput setaf 0; echo  "  d88P Y88b   $usedramicon $(tput sgr0)   $usedram"
tput setaf 0; echo  " d88P   Y88b  $(tput sgr0) "
fi

if [[ $art =~ "Funtoo" ]]; then
tput setaf 3; echo  "                       $user@$host"
tput setaf 5; echo "   __             _    $osicon $(tput sgr0)       $os"
tput setaf 5; echo "  / _|_   _ _ __ | |_  $kernelicon $(tput sgr0)   $kernel"
tput setaf 5; echo " | |_| | | | '_ \| __| $shellicon $(tput sgr0)    $shell"
tput setaf 5; echo " |  _| |_| | | | | |_  $pkgicon $(tput sgr0) $pkg "
tput setaf 5; echo " |_|  \__,_|_| |_|\__| $cpuicon $(tput sgr0)      $cpu"
tput setaf 5; echo "                       $ramicon $(tput sgr0)      $totalram"
tput setaf 5; echo "                       $usedramicon $(tput sgr0)     $usedram"
tput setaf 5; echo "                       $initicon $(tput sgr0)     $init "
fi

if [[ $art = "Linux" ]]; then
tput setaf 3; echo "              $user@$host"
tput setaf 3; echo "     .--.    $osicon $(tput sgr0)       $os"
tput setaf 3; echo "    |o_o |   $kernelicon $(tput sgr0)   $kernel" 
tput setaf 3; echo "    |:_/ |   $shellicon $(tput sgr0)    $shell"
tput setaf 3; echo "   //   \ \  $pkgicon $(tput sgr0) $pkg"
tput setaf 3; echo "  (|     | ) $cpuicon $(tput sgr0)      $cpu"
tput setaf 3; echo " /'|_   _/'\ $ramicon $(tput sgr0)      $totalram"
tput setaf 3; echo " \___)=(___/ $usedramicon $(tput sgr0)     $usedram"
tput setaf 3; echo "             $initicon $(tput sgr0)     $init"
fi

exit 0
