#!/bin/sh
#
#       __      _       _
#  ___ / _| ___| |_ ___| |__
# / __| |_ / _ \ __/ __| '_ \
# \__ \  _|  __/ || (__| | | |
# |___/_|  \___|\__\___|_| |_|
# speedie's stupid fetch tool
# Version something
############################################################
clear

if [[ -f "/etc/os-release" ]]; then
    os="$(cat /etc/os-release)"
elif [[ -f "/System/Library/CoreServices/SystemVersion.plist" ]]; then
	mac="$(cat /System/Library/CoreServices/SystemVersion.plist)" && macmodel="$(sysctl hw.model | sed 's/hw.model: //')"
fi

# Gentoo first because Gentoo is based
if [[ $os =~ "Gentoo" ]]; then
	os="Gentoo" && art="Gentoo"
elif [[ $os =~ "Funtoo" ]]; then
	os="Funtoo" && art="Funtoo"
elif [[ $os =~ "Arch" ]]; then
	os="Arch" && art="Arch"
elif [[ $os =~ "Debian" ]]; then
	os="Debian" && art="Linux"
elif [[ $os =~ "Pear" ]]; then
	os="ShitOS" && art="Linux"
elif [[ $os =~ "Ubuntu" ]]; then
	os="Ubuntu" && art="Linux"
elif [[ $os =~ "Fedora" ]]; then
	os="Fedora" && art="Linux"
elif [[ $os =~ "Cutefish" ]]; then
	os="ShitFish OS" && art="Linux"
elif [[ $os =~ "Manjaro" ]]; then
	os="Manjarno" && art="Linux"
elif [[ $os =~ "ANSI" ]]; then
	os="$(uname -s)" && art="Linux"
elif [[ $mac =~ "Mac OS X" ]]; then
	os="Mac OS X" && art="Mac OS X"
elif [[ $mac =~ "macOS" ]]; then
	os="macOS" && art="Mac OS X"
elif [[ $mac =~ "Project 081" ]]; then
    os="Project 081" && art="Project 081"
fi

# Base
user="$(whoami)"
host="$(hostname)"

# Data
kernel="$(uname -sr)" # Get kernel version
gnu="$(uname -o)"
shell="$(basename "${SHELL}")"
pkg="$(ls -d /var/db/pkg/*/* | wc -l)"

# Label/Icons
kernelicon="KERNEL:"
osicon="DISTRO:"
shellicon="SHELL:"
pkgicon="PACKAGES:"
macicon="MAC:"

os="Linux From Scratch" # For testing only
art="Linux" # For testing only
#tput setaf 3; echo $user@$host" # For testing only

# Display everything to the user!
# NOTE: Ascii must be 8 lines in height!

if [[ $art = "Gentoo" ]]; then
tput setaf 3; echo "                  $user@$host"
tput setaf 5; echo "    dSSSSSb.     $(tput sgr0) "
tput setaf 5; echo " .dSSSSSSSSSb.   $(tput sgr0) "
tput setaf 5; echo " SSSS( )SSSSSSb  $(tput sgr0) $osicon $os $gnu"
tput setaf 5; echo " QSSSSSSSSSSSSSb $(tput sgr0) $kernelicon $kernel"
tput setaf 5; echo "   dSSSSSSSSSSP  $(tput sgr0) $shellicon $shell"
tput setaf 5; echo "  dSSSSSSSSSP    $(tput sgr0) $pkgicon $pkg" 
tput setaf 5; echo " SSSSSSSSSSP     $(tput sgr0) "
tput setaf 5; echo "  QSSSSSSP       $(tput sgr0) "
fi

if [[ $art =~ "Arch" ]]; then
tput setaf 3; echo "                 $user@$host"
tput setaf 6; echo "       .        $(tput sgr0) "
tput setaf 6; echo "      /#\       $(tput sgr0) "
tput setaf 6; echo "     /###\      $(tput sgr0) $osicon $os $gnu"
tput setaf 6; echo "    /p^###\     $(tput sgr0) $kernelicon $kernel"
tput setaf 6; echo "   /##P^q##\    $(tput sgr0) $shellicon $shell"
tput setaf 6; echo "  /##(   )##\   $(tput sgr0) $pkgicon $pkg"
tput setaf 6; echo " /###q#    ,^\  $(tput sgr0) "
tput setaf 6; echo "/P^         ^q\ $(tput sgr0) "
fi

if [[ $art =~ "Project 081" ]]; then
tput setaf 3; echo  "               $user@$host"
tput setaf 6; echo  " Y88b   d88P  $(tput sgr0) "
tput setaf 6; echo  "  Y88b d88P   $(tput sgr0) "
tput setaf 6; echo  "   Y88o88P    $(tput sgr0) $osicon $os"
tput setaf 6; echo  "    Y888P     $(tput sgr0) $kernelicon $kernel"
tput setaf 6; echo  "    d888b     $(tput sgr0) $shellicon $shell"
tput setaf 6; echo  "   d88888b    $(tput sgr0) $macicon $macmodel"
tput setaf 6; echo  "  d88P Y88b   $(tput sgr0) "
tput setaf 6; echo  " d88P   Y88b  $(tput sgr0) "
fi

if [[ $art =~ "Mac OS X" ]]; then
tput setaf 3; echo  "               $user@$host"
tput setaf 0; echo  " Y88b   d88P  $(tput sgr0) "
tput setaf 0; echo  "  Y88b d88P   $(tput sgr0) "
tput setaf 0; echo  "   Y88o88P    $(tput sgr0) $osicon $os"
tput setaf 0; echo  "    Y888P     $(tput sgr0) $kernelicon $kernel"
tput setaf 0; echo  "    d888b     $(tput sgr0) $shellicon $shell"
tput setaf 0; echo  "   d88888b    $(tput sgr0) $macicon $macmodel"
tput setaf 0; echo  "  d88P Y88b   $(tput sgr0) "
tput setaf 0; echo  " d88P   Y88b  $(tput sgr0) "
fi


if [[ $art =~ "Funtoo" ]]; then
tput setaf 3; echo  "                       $user@$host"
tput setaf 5; echo "   __             _   $(tput sgr0) "
tput setaf 5; echo "  / _|_   _ _ __ | |_ $(tput sgr0) "
tput setaf 5; echo " | |_| | | | '_ \| __|$(tput sgr0) $osicon $os $gnu"
tput setaf 5; echo " |  _| |_| | | | | |_ $(tput sgr0) $kernelicon $kernel"
tput setaf 5; echo " |_|  \__,_|_| |_|\__|$(tput sgr0) $shellicon $shell"
tput setaf 5; echo "                      $(tput sgr0) $pkgicon $pkg"
tput setaf 5; echo "                      $(tput sgr0) "
tput setaf 5; echo "                      $(tput sgr0) "
fi

if [[ $art = "Linux" ]]; then
tput setaf 3; echo "              $user@$host"
tput setaf 3; echo "     .--.    $(tput sgr0) "
tput setaf 3; echo "    |o_o |   $(tput sgr0) " 
tput setaf 3; echo "    |:_/ |   $(tput sgr0) $osicon $os $gnu"
tput setaf 3; echo "   //   \ \  $(tput sgr0) $kernelicon $kernel"
tput setaf 3; echo "  (|     | ) $(tput sgr0) $shellicon $shell"
tput setaf 3; echo " /'|_   _/'\ $(tput sgr0) $pkgicon $pkg"
tput setaf 3; echo " \___)=(___/ $(tput sgr0) "
tput setaf 3; echo "             $(tput sgr0) "
fi

echo "" && exit 0
