#!/bin/sh
#
#       __      _       _
#  ___ / _| ___| |_ ___| |__
# / __| |_ / _ \ __/ __| '_ \
# \__ \  _|  __/ || (__| | | |
# |___/_|  \___|\__\___|_| |_|
# speedie's stupid fetch tool
# Version: 0.2
############################################################
# Settings

# Label/Icons
kernelicon="KERNEL:"
osicon="OS:"
shellicon="SHELL:"
pkgicon="PACKAGES:"
macicon="MAC:"
cpuicon="CPU:"
initicon="INIT:"
usedramicon="USED:"
ramicon="RAM:"

##############################
# Code, probably don't edit.

# Get the OS
if [[ -f "/etc/os-release" ]]; then
    os="$(cat /etc/os-release)" # Get the OS on Linux
elif [[ -f "/System/Library/CoreServices/SystemVersion.plist" ]]; then
	mac="$(cat /System/Library/CoreServices/SystemVersion.plist)" && macmodel="$(sysctl hw.model | sed 's/hw.model: //')" # Get the OS (macOS)
fi

# Check what init system the user is using.
if [[ -f "/lib/systemd/systemd" ]]; then
	init="systemd"
elif [[ -f "/sbin/openrc" ]]; then
	init="OpenRC"
elif [[ -f "/usr/local/bin/runsvdir" ]]; then
	init="runit"
elif [[ -f "/usr/bin/s6-rc" ]]; then
	init="s6"
fi

# Check what distro is used.
if [[ $os =~ "Gentoo" ]]; then
	os="Gentoo Linux" && art="Gentoo"
elif [[ $os =~ "Funtoo" ]]; then
	os="Funtoo Linux" && art="Funtoo"
elif [[ $os =~ "Arch" ]]; then
	os="Arch Linux" && art="Arch"
elif [[ $os =~ "Debian" ]]; then
	os="Debian Linux" && art="Linux" # No ASCII art for Debian yet
elif [[ $os =~ "Pear" ]]; then 
	os="ShitOS Linux" && art="Trash" # No ASCII art (trash can) for PearOS
elif [[ $os =~ "Ubuntu" ]]; then
	os="Ubuntu Linux" && art="Linux" # No ASCII art for Ubuntu yet
elif [[ $os =~ "Fedora" ]]; then
	os="Fedora Linux" && art="Linux" # No ASCII art for Fedora yet
elif [[ $os =~ "Cutefish" ]]; then
	os="ShitFish OS Linux" && art="Trash" # No ASCII art (trash can) for Cutefish OS
elif [[ $os =~ "Manjaro" ]]; then
	os="Manjarno Linux" && art="Linux" # No ASCII art for Manjaro yet
elif [[ $os =~ "ANSI" ]]; then
	os="$(uname -s)" && art="Linux" # Linux is the "generic" art
elif [[ $mac =~ "Mac OS X" ]]; then
	os="Mac OS X" && art="Mac OS X"
elif [[ $mac =~ "macOS" ]]; then
	os="macOS" && art="macOS"
elif [[ $mac =~ "Project 081" ]]; then
    os="Project 081" && art="Project 081"
fi

# Base
user="$(whoami)" # whoami returns the user who runs the command
host="$(hostname)" # hostname returns your hostname from /etc/hostname

# Data
kernel="$(uname -sr)" # Get kernel version
shell="$(basename "${SHELL}")"

if [[ -f "/proc/meminfo" ]]; then
	pkg="$(ls -d /var/db/pkg/*/* | wc -l)"
fi

totalram="$(cat /proc/meminfo | grep -i 'memtotal' | grep -o '[[:digit:]]*' | awk '{$1=$1/1024; print $1,"MB";}')"
usedram="$(cat /proc/meminfo | grep -i 'Active:' | grep -o '[[:digit:]]*' | awk '{$1=$1/1024; print $1,"MB";}' | awk 'NR!=2')"

if [[ -f "/System/Library/CoreServices/SystemVersion.plist" ]]; then
totalrammac="$(sysctl hw.memsize | grep -o '[[:digit:]]*' | awk '{$1=$1/1024; print $1,"MB";}')"
cpumac="$(sysctl -n machdep.cpu.brand_string)"
fi

if [[ -f "/usr/bin/uname" ]]; then
	cpu="$(uname -p)"
else
	cpu="$(sysctl -n machdep.cpu.brand_string)"
fi

# Label/Icons
kernelicon="KERNEL:"
osicon="OS:"
shellicon="SHELL:"
pkgicon="PACKAGES:"
macicon="MAC:"
cpuicon="CPU:"
initicon="INIT:"
usedramicon="USED:"
ramicon="RAM:"

#os="PearOS" # For testing only
#art="Trash" # For testing only
#tput setaf 3; echo $user@$host" # For testing only

# Display everything to the user!
# NOTE: Ascii must be 8 lines in height!

if [[ $art = "Gentoo" ]]; then
tput setaf 3; echo "                 $user@$host"
tput setaf 5; echo "    dSSSSSb.     $osicon $(tput sgr0)       $os"
tput setaf 5; echo " .dSSSSSSSSSb.   $kernelicon $(tput sgr0)   $kernel"
tput setaf 5; echo " SSSS( )SSSSSSb  $shellicon $(tput sgr0)    $shell"
tput setaf 5; echo " QSSSSSSSSSSSSSb $pkgicon $(tput sgr0) $pkg"
tput setaf 5; echo "   dSSSSSSSSSSP  $cpuicon $(tput sgr0)      $cpu"
tput setaf 5; echo "  dSSSSSSSSSP    $ramicon $(tput sgr0)      $totalram" 
tput setaf 5; echo " SSSSSSSSSSP     $usedramicon $(tput sgr0)     $usedram "
tput setaf 5; echo "  QSSSSSSP       $initicon $(tput sgr0)     $init"
fi

if [[ $art =~ "Arch" ]]; then
tput setaf 3; echo "                $user@$host"
tput setaf 6; echo "       .        $osicon $(tput sgr0)         $os"
tput setaf 6; echo "      /#\       $kernelicon $(tput sgr0)     $kernel"
tput setaf 6; echo "     /###\      $shellicon $(tput sgr0)      $shell"
tput setaf 6; echo "    /p^###\     $pkgicon $(tput sgr0)   $pkg"
tput setaf 6; echo "   /##P^q##\    $cpuicon $(tput sgr0)        $cpu"
tput setaf 6; echo "  /##(   )##\   $ramicon $(tput sgr0)        $totalram"
tput setaf 6; echo " /###q#    ,^\  $usedramicon $(tput sgr0)       $usedram"
tput setaf 6; echo "/P^         ^q\ $initicon $(tput sgr0)       $init"
fi

if [[ $art =~ "Project 081" ]]; then
tput setaf 3; echo  "              $user@$host"
tput setaf 6; echo  " Y88b   d88P  $osicon $(tput sgr0)     $os"
tput setaf 6; echo  "  Y88b d88P   $kernelicon $(tput sgr0) $kernel"
tput setaf 6; echo  "   Y88o88P    $shellicon $(tput sgr0)  $shell"
tput setaf 6; echo  "    Y888P     $macicon $(tput sgr0)    $macmodel"
tput setaf 6; echo  "    d888b     $cpuicon $(tput sgr0)    $cpumac"
tput setaf 6; echo  "   d88888b    $ramicon $(tput sgr0)    $totalrammac"
tput setaf 6; echo  "  d88P Y88b   $usedramicon $(tput sgr0)   $usedram"
tput setaf 6; echo  " d88P   Y88b  $(tput sgr0) "
fi

if [[ $art =~ "Mac OS X" ]]; then
tput setaf 3; echo  "              $user@$host"
tput setaf 0; echo  " Y88b   d88P  $osicon $(tput sgr0)     $os"
tput setaf 0; echo  "  Y88b d88P   $kernelicon $(tput sgr0) $kernel"
tput setaf 0; echo  "   Y88o88P    $shellicon $(tput sgr0)  $shell"
tput setaf 0; echo  "    Y888P     $macicon $(tput sgr0)    $macmodel"
tput setaf 0; echo  "    d888b     $cpuicon $(tput sgr0)    $cpu"
tput setaf 0; echo  "   d88888b    $ramicon $(tput sgr0)    $totalram"
tput setaf 0; echo  "  d88P Y88b   $usedramicon $(tput sgr0)   $usedram"
tput setaf 0; echo  " d88P   Y88b  $(tput sgr0) "
fi

if [[ $art =~ "macOS" ]]; then
tput setaf 0; echo  " _ __ ___   __ _  ___  $(tput setaf 3;)$user@$host"
tput setaf 0; echo  "| '_ ' _ \ / _' |/ __| $osicon $(tput sgr0)     $os"
tput setaf 0; echo  "| | | | | | (_| | (__  $kernelicon $(tput sgr0) $kernel"
tput setaf 0; echo  "|_| |_|_|_|\__,_|\___| $shellicon $(tput sgr0)  $shell"
tput setaf 0; echo  "     / _ \/ ___|       $macicon $(tput sgr0)    $macmodel"
tput setaf 0; echo  "    | | | \___ \       $cpuicon $(tput sgr0)    $cpu"
tput setaf 0; echo  "    | |_| |___) |      $ramicon $(tput sgr0)    $totalram"
tput setaf 0; echo  "     \___/|____/       $usedramicon $(tput sgr0)   $usedram"
tput setaf 0; echo "$(tput sgr0)"
fi

if [[ $art =~ "Funtoo" ]]; then
tput setaf 3; echo  "                      $user@$host"
tput setaf 5; echo "   __             _    $osicon $(tput sgr0)       $os"
tput setaf 5; echo "  / _|_   _ _ __ | |_  $kernelicon $(tput sgr0)   $kernel"
tput setaf 5; echo " | |_| | | | '_ \| __| $shellicon $(tput sgr0)    $shell"
tput setaf 5; echo " |  _| |_| | | | | |_  $pkgicon $(tput sgr0) $pkg "
tput setaf 5; echo " |_|  \__,_|_| |_|\__| $cpuicon $(tput sgr0)      $cpu"
tput setaf 5; echo "                       $ramicon $(tput sgr0)      $totalram"
tput setaf 5; echo "                       $usedramicon $(tput sgr0)     $usedram"
tput setaf 5; echo "                       $initicon $(tput sgr0)     $init "
fi

if [[ $art =~ "Trash" ]]; then
tput setaf 3; echo  "            $user@$host"
tput setaf 5; echo "  ____n____  $osicon $(tput sgr0)       $os"
tput setaf 5; echo " /         \ $kernelicon $(tput sgr0)   $kernel"
tput setaf 5; echo " -| | | | |- $shellicon $(tput sgr0)    $shell"
tput setaf 5; echo "  | | | | |  $pkgicon $(tput sgr0) $pkg "
tput setaf 5; echo "  | | | | |  $cpuicon $(tput sgr0)      $cpu"
tput setaf 5; echo "  | | | | |  $ramicon $(tput sgr0)      $totalram"
tput setaf 5; echo "  | | | | |  $usedramicon $(tput sgr0)     $usedram"
tput setaf 5; echo "  \-------/  $initicon $(tput sgr0)     $init "
fi

if [[ $art = "Linux" ]]; then
tput setaf 3; echo "             $user@$host"
tput setaf 3; echo "     .--.    $osicon $(tput sgr0)       $os"
tput setaf 3; echo "    |o_o |   $kernelicon $(tput sgr0)   $kernel" 
tput setaf 3; echo "    |:_/ |   $shellicon $(tput sgr0)    $shell"
tput setaf 3; echo "   //   \ \  $pkgicon $(tput sgr0) $pkg"
tput setaf 3; echo "  (|     | ) $cpuicon $(tput sgr0)      $cpu"
tput setaf 3; echo " /'|_   _/'\ $ramicon $(tput sgr0)      $totalram"
tput setaf 3; echo " \___)=(___/ $usedramicon $(tput sgr0)     $usedram"
tput setaf 3; echo "             $initicon $(tput sgr0)     $init"
fi

exit 0


